config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json
  skip_before_filter  :verify_authenticity_token
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    puts "\n\n\n\n---------------product_params: #{product_params.inspect}"
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        render :text => "Error occured!".html_safe
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajax In Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
	<p></p>
	<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/products/_create.js.erb
$(function () {
  $('#commit').click(function () {
    var name = $("#product_name").val();
    var price = $("#product_price").val();
    var json_data = {product: {name: name, price: price}};
    $.ajax({
      type: "POST",
      contentType: "application/json; charset=utf-8",
      url: "/products",
      dataType: "json",
      data: JSON.stringify(json_data),
      success: function (response) {
        $("#product_name").val('')
        $("#product_price").val('')
        console.log(response);
      },
      error: function (error) {
        console.log(error);
      }
    });
  });
});

app/views/products/_form.html - Copy.erb
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
    <%= form_tag ("/product/create", :method=> "post"), html: {class: "form-vertical", role: "form"} %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= label_tag "Name", for: "product_name" %><br>
        <%= text_field_tag, name: "product_name", id: "product_name", class: "form-control"%>
      </div>
      <div class="form-group">
        <%= label_tag "Price", for: "product_price" %><br>
        <%= text_field_tag, name: "product_price", id: "product_price", class: "form-control"%>
      </div>
      <%= submit_tag "Create product", class: "btn btn-success", id: "commit" %>
      <%= link_to 'Back', products_path, class: "btn btn-danger", style: 'float: right;'%>
    <% end %>
  </div>
</div>

app/views/products/_form_edit.html.erb
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
    <%= form_for @product, html: {class: "form-vertical", role: "form"} do |f| %>
      <div class="form-group">
        <%= f.label :name%><br>
        <%= f.text_field :name, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.label :price %><br>
        <%= f.text_field :price, class: "form-control"%>
      </div>
      <%= f.submit "Update product", class: "btn btn-success", id: "commit" %>
    <% end %>
  </div>
</div>

app/views/products/_form_new.html.erb
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
    <%= form_tag ("#"), :onSubmit => "return false", class: "form-vertical", role: "form" do %>
      <div class="form-group">
        <%= label_tag "Name"%><br>
        <%= text_field_tag "product_name", nil, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= label_tag "Price" %><br>
        <%= text_field_tag "product_price", nil, class: "form-control"%>
      </div>
      <%= submit_tag "Create product", class: "btn btn-success", id: "commit" %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', @product, class: "btn btn-default"%> |
<%= link_to 'Back', products_path, class: "btn btn-danger"%>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>
<br>
<%= link_to 'New Product', new_product_path, class: "btn btn-primary" %>
<br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= '$' + product.price.to_s %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form_new' %>
<%= link_to 'Back', products_path, class: "btn btn-danger"%>
<script >
$(function () {
	$('#commit').click(function () {
		var name = $("#product_name").val();
		var price = $("#product_price").val();
		var json_data = {product: {name: name, price: price}};
		$.ajax({
		  type: "POST",
		  contentType: "application/json; charset=utf-8",
		  url: "/products",
		  dataType: "json",
		  data: JSON.stringify(json_data),
		  success: function (response) {
		  	$("#product_name").val('')
		  	$("#product_price").val('')
		  	console.log(response);
		  },
		  error: function (error) {
		    console.log(error);
		  }
		});
	});
});
</script>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product), class: "btn btn-primary" %> |
<%= link_to 'Back', products_path, class: "btn btn-danger"%>